# Generated by Django 3.0.3 on 2020-02-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('variable', models.CharField(max_length=100)),
                ('expected_value', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
